# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.224.2/containers/ubuntu/.devcontainer/base.Dockerfile

# [Choice] Ubuntu version (use hirsuite or bionic on local arm64/Apple Silicon): hirsute, focal, bionic
#ARG VARIANT="hirsute"
#FROM mcr.microsoft.com/vscode/devcontainers/base:0-${VARIANT}
ARG NODE_VERSION=16
FROM ubuntu:20.04

# [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>

# Install ant and wget to install Salesforce CLI
RUN apt-get update && \
    apt-get install -y ant && \
    apt-get install -y xz-utils && \
    apt-get install -y wget && \
    apt-get install -y git &&  \
    apt-get install -y unzip &&  \
    apt-get install -y sudo &&  \
    apt install -y jq &&  \
    rm -rf /var/lib/apt/lists/*

# Install latest Node.js
# https://gist.github.com/isaacs/579814#file-node-and-npm-in-30-seconds-sh
RUN mkdir ~/node-latest-install && cd $_ && \
    apt-get update -y && \
    apt-get upgrade -y && \
    apt-get install -y && \
    curl -sL https://deb.nodesource.com/setup_14.x | bash - && \
    apt-get install -y nodejs

# Install PowerShell and their dependencies
RUN apt-get install -y wget apt-transport-https software-properties-common && \
    wget -q https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb && \
    dpkg -i packages-microsoft-prod.deb && \
    apt-get update && \
    apt-get install -y powershell && \
    rm -f packages-microsoft-prod.deb

# Install NPM
RUN apt-get update && apt-get install -y \
    software-properties-common \
    npm
RUN npm install npm@latest -g && \
    npm install n -g && \
    n latest
RUN node -v && \
    npm -v

# Install eslint dependencies
WORKDIR /usr/app
COPY ./ /usr/app
RUN echo 'y' | npm install eslint @babel/core @babel/eslint-parser @lwc/eslint-plugin-lwc --save-dev

#Fix for azure devops to install all npm packages in a custom location
RUN mkdir /usr/app/npm-global && \
    npm config set prefix /usr/app/npm-global

# Install Salesforce CLI and Other SFDX Plugins wiht NPM. Update the SF version with newer versions or keep it empty for latest
WORKDIR /usr/app
RUN export PATH="$PATH:/usr/app/npm-global/bin" && \
    npm install @salesforce/cli@2.22.7 --prefix /usr/app/npm-global --global && \
    echo 'y' | sf plugins install @salesforce/sfdx-scanner@latest-beta && \
    npm install --global vlocity && \
    echo 'y' | sf plugins install sfdx-git-delta && \
    echo 'y' | sf plugins install lightning-flow-scanner && \
    sf --version

# Install PMD. Get link for newer version from https://github.com/pmd/pmd/releases
WORKDIR /usr/app
RUN wget https://github.com/pmd/pmd/releases/download/pmd_releases%2F7.0.0-rc4/pmd-dist-7.0.0-rc4-bin.zip && \
    unzip pmd-dist-7.0.0-rc4-bin.zip && \
    rm -f pmd-dist-7.0.0-rc4-bin.zip

#Changing root password so we can execute sudo later
RUN echo 'root:Docker!' | chpasswd

# Updating PATH so we can access all command lines directly from key words for ALL users in Docker
RUN chmod 777 /root && chmod 777 /root/.local && chmod 777 /root/.local/share/ && chmod 777 /root/.local/share/sf/ && chmod 777 /root/.local/share/sf/package.json
RUN chmod -R 777 /root/.sf/
RUN chmod -R 777 /root/.npm/
ENV PATH="$PATH:/usr/app/pmd-bin-7.0.0-rc4/bin"
ENV PATH="$PATH:/usr/app/npm-global/bin"
RUN echo "export PATH=${PATH}" >> /root/.bashrc
RUN echo "export PATH=${PATH}" >> /etc/bash.bashrc
RUN echo "export PATH=${PATH}" >> /etc/profile
RUN echo "export PATH=${PATH}" > /etc/environment